name: Staging Run Python Code

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          'Box1/darvas_logic',
          'Box2/darvas_logic',
          'Box2/darvas_logic'
        ]

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Debug Environment Variables
      run: |
        echo "GOOGLE_CREDENTIALS_JSON: $GOOGLE_CREDENTIALS_JSON"
        echo "GOOGLE_CLIENT_SECRETS_JSON: $GOOGLE_CLIENT_SECRETS_JSON"

    - name: Set up Google credentials
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_CLIENT_SECRETS_JSON: ${{ secrets.GOOGLE_CLIENT_SECRETS_JSON }}
      run: |
        echo "${GOOGLE_CREDENTIALS_JSON}" > credentials.json
        echo "${GOOGLE_CLIENT_SECRETS_JSON}" > client_secrets.json
        export GOOGLE_CREDENTIALS_JSON=$PWD/credentials.json
        export GOOGLE_CLIENT_SECRETS_JSON=$PWD/client_secrets.json
        
    - name: Debug - Check if files are created
      run: |
        ls -la
        cat credentials.json
        cat client_secrets.json

    - name: Debug Credentials File
      run: |
        head -n 10 credentials.json
        head -n 10 client_secrets.json    

    - name: Validate JSON Files
      run: |
       python -c 'import json; json.load(open("credentials.json"))'
       python -c 'import json; json.load(open("client_secrets.json"))'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      run: |
        python ${{ matrix.script }}

  run-drive-reports:
    runs-on: ubuntu-latest
    needs: run-python

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Set up Google credentials
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        GOOGLE_CLIENT_SECRETS_JSON: ${{ secrets.GOOGLE_CLIENT_SECRETS_JSON }}
      run: |
        echo "${GOOGLE_CREDENTIALS_JSON}" > credentials.json
        echo "${GOOGLE_CLIENT_SECRETS_JSON}" > client_secrets.json
        export GOOGLE_CREDENTIALS_JSON=$PWD/credentials.json
        export GOOGLE_CLIENT_SECRETS_JSON=$PWD/client_secrets.json
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run the Drive Reports Concatenate script
    #   run: |
    #     python improve_the_email_with_compring.py

    # - name: Run the new history
    #   run: |
    #     python new_history.py